version: "3"
services:
  onos:
    image: charlesmcchan/onos:20191022
    container_name: onos
    privileged: true
    env_file:
      - .env
    environment:
      - ONOS_APPS=drivers,openflow,segmentrouting,fpm,dhcprelay,routeradvertisement,hostprobingprovider,t3
    volumes:
      - "./volume/onos:/root/onos/volume"
    networks:
      - mgmt
    ports:
      - "18101:8101"
      - "18181:8181"
    tty: true
    stdin_open: true
    entrypoint: /root/onos/volume/entrypoint.sh

  start_onos:
    image: stefanevinance/wait-for-200
    depends_on:
      - onos
    env_file:
      - .env
    networks:
      - mgmt

  mininet:
    image: charlesmcchan/mn-trellis:20191022
    container_name: mininet
    privileged: true
    volumes:
      - "./volume/mininet:${CFG_PATH}"
    depends_on:
      - start_onos
    env_file:
      - .env
    environment:
      - EXTERNAL_VOLUME=${CFG_PATH}
      - NETCFG_FILE=${CFG_FILE}
    networks:
      - mgmt
    tty: true
    stdin_open: true
    entrypoint: /root/entrypoint.sh

networks:
  mgmt:
    driver: "bridge"
